set bg=dark
set noerrorbells
set tabstop=4 softtabstop=4
set guicursor=n:block
set guicursor=i:ver25
set shiftwidth=4
set expandtab
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set relativenumber
set nohlsearch
set smartindent
set colorcolumn=80
set clipboard+=unnamedplus
set autoread
