vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.tabstop = 4
vim.o.relativenumber = true
vim.o.smartindent = true
vim.opt.hlsearch = false
vim.o.wrap = true
vim.o.undodir = vim.fn.stdpath("config") .. "/undodir"
vim.o.undofile = true
vim.opt.errorbells = false
vim.o.splitright = true
vim.o.autoread = true
vim.o.clipboard = "unnamedplus"
vim.o.mouse = "a"
vim.o.termguicolors = true
vim.o.incsearch = true
vim.o.autochdir = true
vim.o.cursorline = true
vim.o.completeopt = "menuone,noinsert,noselect"
vim.g.mapleader = " "
